- name: Setup nodes
  hosts: workers
  tasks:
   - name: Create aws directory
     ansible.builtin.file:
       path: "{{ item }}"
       state: directory
       mode: '0755'
     with_items:
       - "{{ aws_base_path }}/backend"
       - "{{ aws_base_path }}/vm-data"

   - name: Copy server
     ansible.builtin.copy:
       src: "{{ item }}"
       dest: "{{ aws_base_path }}/backend/"
       mode: '0755'
     with_items:
       - target/release/vm-launcher
       - alpine.qcow2

   - name: Create config file
     ansible.builtin.copy:
       content: |
         [storage]
         qcow2_dir = "{{ aws_base_path }}/vm-data"
         metadata_dir = "{{ aws_base_path }}/vm-data"
       dest: "{{ aws_base_path }}/backend/config.toml"

   - name: Create systemd service file
     ansible.builtin.copy:
       content: |
         [Unit]
         Description=Backend Rust Server
         After=network.target

         [Service]
         Type=simple
         User=andy
         WorkingDirectory={{ aws_base_path }}/backend
         ExecStart={{ aws_base_path }}/backend/vm-launcher
         Restart=always
         RestartSec=10
         Environment="RUST_LOG=info"
         Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
         [Install]
         WantedBy=multi-user.target
       dest: /etc/systemd/system/vm-launcher.service
       mode: '0644'
     become: yes

   - name: Reload systemd daemon
     ansible.builtin.systemd:
       daemon_reload: yes
     become: yes

   - name: Enable and start Rust backend service
     ansible.builtin.systemd:
       name: vm-launcher
       enabled: yes
       state: restarted
     become: yes
