- name: Setup nodes
  hosts: workers
  tasks:
   - name: Create aws directory
     ansible.builtin.file:
       path: "{{ item }}"
       state: directory
       mode: '0755'
     with_items:
       - /home/andy/aws/backend
       - /home/andy/aws/vm-data

   - name: Copy server
     ansible.builtin.copy:
       src: "{{ item }}"
       dest: /home/andy/aws/backend/
       mode: '0755'
     with_items:
       - target/release/vm-launcher
       - alpine.qcow2

   - name: Copy config file
     ansible.builtin.copy:
       src: config.ci.toml
       dest: /home/andy/aws/backend/config.toml

