- name: Setup nodes
  hosts: workers
  tasks:
   - name: Install qemu
     ansible.builtin.apt:
       name: qemu-system-x86
       state: present
       update_cache: yes
     become: yes

   - name: Create /etc/qemu directory
     ansible.builtin.file:
       path: /etc/qemu
       state: directory
       mode: '0755'
     become: yes

   - name: Allow bridge helper to use br0
     ansible.builtin.copy:
       content: "allow br0\n"
       dest: /etc/qemu/bridge.conf
       owner: root
       group: kvm
       mode: '0640'
     become: yes

   - name: Add andy to kvm group
     ansible.builtin.user:
       name: andy
       groups: kvm
       append: yes
     become: yes

   - name: Ensure qemu-bridge-helper is setuid root and group kvm
     ansible.builtin.file:
       path: /usr/lib/qemu/qemu-bridge-helper
       owner: root
       group: kvm
       mode: '4750'
     become: yes

   - name: Create aws directory
     ansible.builtin.file:
       path: "{{ item }}"
       state: directory
       mode: '0755'
     with_items:
       - "{{ aws_base_path }}/backend"
       - "{{ aws_base_path }}/vm-data"
       - "{{ aws_base_path }}/volume-data"
       - "{{ aws_base_path }}/volume-data/volumes"

   - name: Copy server
     ansible.builtin.copy:
       src: "{{ item }}"
       dest: "{{ aws_base_path }}/backend/"
       mode: '0755'
     with_items:
       - target/release/vm-launcher
       - alpine.qcow2

   - name: Create config file
     ansible.builtin.copy:
       content: |
         listen_ip = "{{ ansible_host }}"
         proxy_url = "http://10.0.0.1:8080"
         network_mode = "bridge"
         [storage]
         qcow2_dir = "{{ aws_base_path }}/vm-data"
         metadata_dir = "{{ aws_base_path }}/vm-data"
         volume_data_dir = "{{ aws_base_path }}/volume-data"
       dest: "{{ aws_base_path }}/backend/config.toml"

   - name: Create systemd service file
     ansible.builtin.copy:
       content: |
         [Unit]
         Description=Backend Rust Server
         After=network.target

         [Service]
         Type=simple
         User=root
         WorkingDirectory={{ aws_base_path }}/backend
         ExecStart={{ aws_base_path }}/backend/vm-launcher
         Restart=always
         RestartSec=10
         Environment="RUST_LOG=info"
         Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
         [Install]
         WantedBy=multi-user.target
       dest: /etc/systemd/system/vm-launcher.service
       mode: '0644'
     become: yes

   - name: Reload systemd daemon
     ansible.builtin.systemd:
       daemon_reload: yes
     become: yes

   - name: Enable and start Rust backend service
     ansible.builtin.systemd:
       name: vm-launcher
       enabled: yes
       state: restarted
     become: yes
