- name: Setup controller
  become: yes
  hosts: controller
  tasks:
   - name: Create aws directory
     ansible.builtin.file:
       path: /home/andy/aws/proxy
       state: directory
       mode: '0755'

   - name: Copy proxy binary
     ansible.builtin.copy:
       src: target/release/proxy
       dest: /home/andy/aws/proxy
       mode: '0755'

   - name: Copy config file
     ansible.builtin.copy:
       src: config.toml
       dest: /home/andy/aws/proxy/config.toml

   - name: Create systemd service file
     ansible.builtin.copy:
       content: |
         [Unit]
         Description=Proxy Rust Server
         After=network.target

         [Service]
         Type=simple
         User=andy
         WorkingDirectory=/home/andy/aws/proxy
         ExecStart=/home/andy/aws/proxy/proxy
         Restart=always
         RestartSec=10
         Environment="RUST_LOG=info"

         [Install]
         WantedBy=multi-user.target
       dest: /etc/systemd/system/proxy.service
       mode: '0644'

   - name: Reload systemd daemon
     ansible.builtin.systemd:
       daemon_reload: yes

   - name: Enable and start Rust backend service
     ansible.builtin.systemd:
       name: proxy
       enabled: yes
       state: restarted
